### ISSUE TITLE
a few conversion questions: 3D array, float32 

### ISSUE THREAD

**Issue by sharifzadeh** [diffplug/matfilerw#24]
1) What's the most efficient way to write a 3D array into a Matlab file?
Should I convert the 3D array into 2D or 1D, create a new instance of MLDouble object, and then pass the 2D or 1D array and finally create a MatFileWriter object?

2) Is it possible to create a mat file within float32 type rather than double (i.e. float[][] array)?

Thanks.

**Comment by nedtwigg** [comment]
1) The most efficient way will be whatever does the least copying. I think you can write the 3D array directly, you shouldn't have to convert it into 1D or 2D.
2) I think you can use `float[]` instead of `double[]`.

Regardless, I would *definitely* use [MFL](https://github.com/HebiRobotics/MFL) instead of MatFileRW. MFL is strictly superior, there's no good reason to use MatFileRW any more.
